name: Assign Reviewers
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: assign reviewers
        shell: bash
        continue-on-error: true
        run: |
          echo $GITHUB_CONTEXT
          # gh pr edit ${{ github.event.pull_request.number }} --add-reviewer peoplefun/platform-tech-editors-client
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.event.pull_request.base.repo.name }}