name: Assign Reviewers
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: context
        shell: bash
        continue-on-error: true
        run: |
          echo $GITHUB_CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: assign reviewers
        shell: bash
        continue-on-error: true
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer ianpilipski
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
